return { --WIP
    --Basic Patterns
    ["qaq"] = "Mind's Reflection",
    ["aa"] = "Compass' Purification I",
    ["dd"] = "Compass' Purification II",
    ["wa"] = "Alidade's Purification",
    ["wqaawdd"] = "Archer's Distillation",
    ["weddwaa"] = "Architect's Distillation",
    ["weaqa"] = "Scout's Distillation",
    ["de"] = "Reveal",
    ["awq"] = "Stadiometer's Prfn.",
    ["wq"] = "Pace Purification",
    --Mathematics
    ["waaw"] = "Additive Distillation",
    ["wddw"] = "Subtractive Distillation",
    ["waqaw"] = "Multiplicative Dstl.",
    ["wdedw"] = "Division Dstl.",
    ["wqaqw"] = "Length Purification",
    ["wedew"] = "Power Distillation",
    ["ewq"] = "Floor Purification",
    ["qwe"] = "Ceiling Purification",
    ["eqqqqq"] = "Vector Exaltation",
    ["qeeeee"] = "Vector Disintegration",
    ["addwaad"] = "Modulus Distillation",
    ["qqqqqaww"] = "Axial Purification",
    ["eqqq"] = "Entropy Reflection",
    --Constants
    ["aqae"] = "True Reflection",
    ["dedq"] = "False Reflection",
    ["d"] = "Nullary Reflection",
    ["qqqqq"] = "Vector Reflection Zero",
    ["qqqqqea"]="Vector Rfln. +X",
    ["eeeeeqa"]="Vector Rfln. -X",
    ["qqqqqew"]="Vector Rfln. +Y",
    ["eeeeeqw"]="Vector Rfln. -Y",
    ["qqqqqed"]="Vector Rfln. +Z",
    ["eeeeeqd"]="Vector Rfln. -Z",
    ["eawae"]="Circle's Reflection",
    ["qdwdq"]="Arc's Reflection",
    ["aaq"]="Euler's Reflection",
    --Dimensional Iotas
    ["wqwqwqwqwqwaeqqe"]="Spacial Reflection",
    ["wqwqwqwqwqwaqeeq"]="Spacial Reflection II",
    --Item Frame Patterns
    ["wwawwqwwawwaeae"]="Decorator's Purification",
    ["wwawwqwwawwaqdq"]="Decorator's Gambit",
    --Status iotas
    ["qqqqqedwd"]="Apothecary's Prfn.",
    ["eeeeeqawa"]="Apothecary's Prfn. II",
    ["qqqqqedwdwd"]="Pharmacist's Prfn.",
    ["eeeeeqawawa"]="Pharmacist's Prfn. II",
    ["eaeeeeeae"]="Entity Distillation: Status",
    ["ewqqqqqwe"]="Zone Exltn.: Status",
    ["qweeeeewq"]="Zone Exltn.: Not-Status",
    ["eeeeedaqdewed"]="Cleanse Status",
    --stack manipulation
    ["a"]="Novice's Gambit",
    ["aawdd"]="Jester's Gambit",
    ["aaeaa"]="Rotation Gambit",
    ["ddqdd"]="Rotation Gambit II",
    ["aadaa"]="Gemini Decomposition",
    ["aaedd"]="Prospector's Gambit",
    ["ddqaa"]="Undertaker's Gambit",
    ["aadaadaa"]="Gemini Gambit",
    ["addadaaw"]="Dioscuri Gambit",
    ["qwaeawqaeaqa"]="Flock's Reflection",
    ["ddad"]="Fisherman's Gambit",
    ["aada"]="Fisherman's Gambit II",
    ["qaawdde"]="Swindler's Gambit",
    --Logical operations
    ["dw"]="Negation Purification",
    ["aw"]="Augur's Purification",
    ["waw"]="Disjunction Distillation",
    ["wdw"]="Conjunction Distillation",
    ["dwa"]="Exclusion Distillation",
    ["awdd"]="Augur's Exaltation",
    ["ad"]="Equality Distillation",
    ["da"]="Inequality Distillation",
    ["e"]="Maximus Distillation",
    ["q"]="Minimus Distillation",
    ["ee"]="Maximus Distillation II",
    ["qq"]="Minimus Distillation II",
    --Entities
    ["qqqqqdaqa"]="Entity Purification",
    ["qqqqqdaqaawa"]="Entity Prfn.: Animal",
    ["qqqqqdaqaawq"]="Entity Prfn.: Monster",
    ["qqqqqdaqaaww"]="Entity Prfn.: Item",
    ["qqqqqdaqaawe"]="Entity Prfn.: Player",
    ["qqqqqdaqaawd"]="Entity Prfn.: Living",
    ["qqqqqwdeddwa"]="Zone Dstl.: Animal",
    ["eeeeewaqaawa"]="Zone Dstl.: Non-Animal",
    ["qqqqqwdeddwq"]="Zone Dstl.: Monster",
    ["eeeeewaqaawq"]="Zone Dstl.: Non-Monster",
    ["qqqqqwdeddww"]="Zone Dstl.: Item",
    ["eeeeewaqaaww"]="Zone Dstl.: Non-Item",
    ["qqqqqwdeddwe"]="Zone Dstl.: Player",
    ["eeeeewaqaawe"]="Zone Dstl.: Non-Player",
    ["qqqqqwdeddwd"]="Zone Dstl.: Living",
    ["eeeeewaqaawd"]="Zone Dstl.: Non-Living",
    ["qqqqqwded"]="Zone Dstl.: Any",
    --Hotbar Manipulation
    ["qwawqwa"]="Handy Reflection",
    ["dwewdwe"]="Handy Gambit",
    ["qwawqwadawqwa"]="Handoff",
    --List Manipulation
    ["deeed"]="Selection Distillation",
    ["qaeaqwded"]="Selection Exaltation",
    ["edqde"]="Integration Distillation",
    ["qaeaq"]="Combination Distillation",
    ["qqaeaae"]="Vacant Reflection",
    ["adeeed"]="Single's Purification",
    ["aqaeaq"]="Abacus Purification",
    ["qqqaede"]="Retrograde Purification",
    ["dedqde"]="Locator's Distillation",
    ["edqdewaqa"]="Excisor's Distillation",
    ["wqaeaqw"]="Surgeon's Exaltation",
    ["ewdqdwe"]="Flock's Gambit",
    ["qwaeawq"]="Flock's Disintegration",
    ["ddewedd"]="Speaker's Distillation",
    ["aaqwqaa"]="Speaker's Decomposition",
    --Pattern escaping
    ["qqqaw"]="Consideration",
    ["qqq"]="Introspection",
    ["eee"]="Retrospection",
    --Reading and writing
    ["aqqqqq"]="Scribe's Reflection",
    ["deeeee"]="Scribe's Gambit",
    ["wdwqwqwqwqwqw"]="Chronicler's Prfn.",
    ["wdwewewewewew"]="Chronicler's Gambit",
    ["aqqqqqe"]="Auditor's Reflection",
    ["deeeeeq"]="Assessor's Reflection",
    ["wdwqwqwqwqwqwew"]="Auditor's Purification",
    ["wdwewewewewewqw"]="Assessor's Purification",
    ["eqqwawqaaw"]="Huginn's Gambit",
    ["qeewdweddw"]="Muninn's Reflection",
    --advanced mathematics
    ["qqqqqaa"]="Sine Purification",
    ["qqqqqad"]="Cosine Purification",
    ["wqqqqqadq"]="Tangent Purification",
    ["ddeeeee"]="Inverse Sine Prfn.",
    ["adeeeee"]="Inverse Cosine Prfn.",
    ["eadeeeeew"]="Inverse Tangent Prfn.",
    ["eqaqe"]="Logarithmic Distillation",
    --Sets
    ["waweaqa"]="Unifying Distillation",
    ["wdweaqa"]="Intersection Distillation",
    ["dwaeaqa"]="Exclusionary Distillation",
    ["dweaqa"]="Inversion Purification",
    ["aweaqa"]="Uniqueness Purification",
    --Meta-evaluation
    ["deaqq"]="Hermes' Gambit",
    ["dadad"]="Thoth's Gambit",
    ["aqdee"]="Charon's Gambit"
}